### ISSUE TITLE
stringify adds leading newline

### ISSUE THREAD

**Issue by petemill** [dotnil/ssh-config#6]
`.parse` cannot parse the output of `.stringify` as it outputs with a leading newline.

Here is a reproducible case:

```
let sshConfig = require('ssh-config')
let config = sshConfig.parse('');
config.append({ Host: '*', IdentifyFile: '~/.ssh/all' });
let output = sshConfig.stringify(config);
```

This produces an output with a leading newline. If we then try and parse that output with `.parse`, we get a corrupted object (which is probably another issue). If we remove the newline manually, `.parse` works correctly.

I'm thinking the issue is with `.stringify`

**Comment by petemill** [comment]
If this fix could be merged and published to npm @dotnil , that would be great. Thanks

**Comment by dotnil** [comment]
@petemill I tried to reproduce the other issue you mentioned with the code below but with no luck.

```js
var obj = sshConfig.parse('')
obj.append({ Host: '*', IdentifyFile: '~/.ssh/all' })
console.log(sshConfig.parse(sshConfig.stringify(obj)))
// { '0': { Host: '*', IdentifyFile: '~/.ssh/all' } }
```

Theoretically, an leading newline in the text being fed to `sshConfig.parse` shouldn't cause any issue because the text will be trimmed first. see https://github.com/dotnil/ssh-config/blob/master/index.js#L168
